name: Build App
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
      - name: Upload Static Build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - name: Finished
        run: echo "Build Finished"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Get Build
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Configure S3 credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy to S3
        run: aws s3 sync dist/ s3://disney-app

